name: hypergraph
channels:
  - defaults
dependencies:
  - affine==2.4.0
  - argparse==1.4.0
  - asciitree==0.3.3
  - attrs==23.1.0
  - batchgenerators==0.25
  - boto3==1.28.45
  - botocore==1.31.45
  - click-plugins==1.1.1
  - cligj==0.7.2
  - cmake==3.26.4
  - ctk-cli==1.5
  - dicom2nifti==2.4.8
  - dicomweb-client==0.59.1
  - dill==0.3.6
  - diskcache==5.6.3
  - distributed==2021.10.0
  - entrypoints==0.4
  - fasteners==0.18
  - filelock==3.12.2
  - future==0.18.3
  - gdal==3.8.0
  - girder-client==3.1.22
  - girder-slicer-cli-web==1.3.5
  - glymur==0.12.8
  - greenlet==2.0.2
  - histolab==0.6.0
  - histomicstk==1.2.10
  - histoqc==2.1.post120+g40b59ef
  - importlib-metadata==6.7.0
  - linecache2==1.0.0
  - lit==16.0.6
  - lxml==4.9.3
  - mapnik==4.0.0
  - markupsafe==2.1.3
  - medpy==0.4.0
  - mpmath==1.3.0
  - msgpack==1.0.5
  - nd2==0.7.2
  - nibabel==5.1.0
  - nimfa==1.4.0
  - nnunet==1.7.1
  - numcodecs==0.11.0
  - numpy==1.23.0
  - opencv-python==4.7.0.72
  - opencv-python-headless==4.8.0.76
  - openslide-python==1.2.0
  - palettable==3.3.3
  - pkgconfig==1.5.5
  - pkgutil-resolve-name==1.3.10
  - psutil==5.9.5
  - pydicom==2.4.1
  - pylibtiff==0.5.1.1
  - pyproj==3.5.0
  - python-bioformats==4.0.7
  - python-gdcm==3.0.22
  - python-javabridge==4.0.3
  - pyvips==2.2.1
  - rasterio==1.3.8
  - referencing==0.30.2
  - requests-toolbelt==1.0.0
  - resource-backed-dask-array==0.1.0
  - retrying==1.3.4
  - rpds-py==0.10.2
  - s3transfer==0.6.2
  - scikit-learn==1.2.2
  - scipy==1.8.1
  - shapely==2.0.1
  - simpleitk==2.2.1
  - sklearn==0.0.post5
  - snuggs==1.4.7
  - sortedcontainers==2.4.0
  - sqlalchemy==2.0.20
  - sympy==1.12
  - tblib==2.0.0
  - threadpoolctl==3.1.0
  - tifftools==1.3.12
  - torch==2.0.1
  - torchaudio==2.0.2
  - torchvision==0.15.2
  - traceback2==1.4.0
  - triton==2.0.0
  - typing-extensions==4.6.3
  - unittest2==1.1.0
  - wsidicom==0.11.0
  - zarr==2.16.1
  - zict==3.0.0
